webtalk_init -webtalk_dir /home/frizik/MOPEVM/fpga/Blink/Blink.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-02-19 22:17:20" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2hd0oeiks61mveh2ubs1blnnb9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.3_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1350.873 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1582137914000" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.3" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key Device -value "7a35ti" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1582137914000"
webtalk_add_data -client sdk -key uid -value "1582138137000" -context "sdk\\\\bsp/1582138137000"
webtalk_add_data -client sdk -key hwid -value "1582137914000" -context "sdk\\\\bsp/1582138137000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1582138137000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1582138137000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1582138137000"
webtalk_add_data -client sdk -key uid -value "1582138138000" -context "sdk\\\\application/1582138138000"
webtalk_add_data -client sdk -key hwid -value "1582137914000" -context "sdk\\\\application/1582138138000"
webtalk_add_data -client sdk -key bspid -value "1582138137000" -context "sdk\\\\application/1582138138000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1582138138000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1582138138000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1582138138000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1582138138000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1582138138000"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1582138138000"
webtalk_add_data -client sdk -key projSize -value "97.0615234375" -context "sdk\\\\application/1582138138000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1582139840304"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1582139840304"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1582139840304"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1582139840304"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1582139840304"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1582139840304"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1582139840304"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1582139840304"
webtalk_transmit -clientid 2599562924 -regid "" -xml /home/frizik/MOPEVM/fpga/Blink/Blink.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/frizik/MOPEVM/fpga/Blink/Blink.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/frizik/MOPEVM/fpga/Blink/Blink.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
